2022-06-07 13:37:33,176 INFO    BackendThr:161716 [internal.py:wandb_internal():92] W&B internal server running at pid: 161716, started at: 2022-06-07 13:37:33.175879
2022-06-07 13:37:33,176 INFO    MainThread:161716 [wandb_init.py:init():534] backend started and connected
2022-06-07 13:37:33,176 DEBUG   MainThread:161716 [config_util.py:dict_from_config_file():102] no default config file found in config-defaults.yaml
2022-06-07 13:37:33,177 INFO    MainThread:161716 [wandb_init.py:init():598] updated telemetry
2022-06-07 13:37:33,179 INFO    WriterThread:161716 [datastore.py:open_for_write():77] open: C:\Users\Jordan\Learning\UVM\Research Projects\Novel-Feature-Detector\wandb\offline-run-20220607_133733-1evgpjk3\run-1evgpjk3.wandb
2022-06-07 13:37:33,364 INFO    MainThread:161716 [wandb_init.py:init():660] starting run threads in backend
2022-06-07 13:37:33,367 DEBUG   HandlerThread:161716 [handler.py:handle_request():141] handle_request: run_start
2022-06-07 13:37:33,379 DEBUG   HandlerThread:161716 [meta.py:__init__():37] meta init
2022-06-07 13:37:33,379 DEBUG   HandlerThread:161716 [meta.py:__init__():51] meta init done
2022-06-07 13:37:33,379 DEBUG   HandlerThread:161716 [meta.py:probe():211] probe
2022-06-07 13:37:33,396 DEBUG   HandlerThread:161716 [meta.py:_setup_git():201] setup git
2022-06-07 13:37:33,507 DEBUG   HandlerThread:161716 [meta.py:_setup_git():208] setup git done
2022-06-07 13:37:33,507 DEBUG   HandlerThread:161716 [meta.py:_save_pip():55] save pip
2022-06-07 13:37:33,508 DEBUG   HandlerThread:161716 [meta.py:_save_pip():69] save pip done
2022-06-07 13:37:33,508 DEBUG   HandlerThread:161716 [meta.py:_save_conda():76] save conda
2022-06-07 13:37:33,510 ERROR   HandlerThread:161716 [meta.py:_save_conda():85] Error saving conda packages
Traceback (most recent call last):
  File "C:\Users\Jordan\anaconda3\envs\EC2\lib\site-packages\wandb\sdk\internal\meta.py", line 81, in _save_conda
    subprocess.call(
  File "C:\Users\Jordan\anaconda3\envs\EC2\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Jordan\anaconda3\envs\EC2\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Jordan\anaconda3\envs\EC2\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2022-06-07 13:37:33,512 DEBUG   HandlerThread:161716 [meta.py:_save_conda():86] save conda done
2022-06-07 13:37:33,512 DEBUG   HandlerThread:161716 [meta.py:probe():249] probe done
2022-06-07 13:37:33,517 INFO    MainThread:161716 [wandb_run.py:_console_start():1896] atexit reg
2022-06-07 13:37:33,517 INFO    MainThread:161716 [wandb_run.py:_redirect():1769] redirect: SettingsConsole.WRAP
2022-06-07 13:37:33,518 INFO    MainThread:161716 [wandb_run.py:_redirect():1806] Wrapping output streams.
2022-06-07 13:37:33,518 INFO    MainThread:161716 [wandb_run.py:_redirect():1830] Redirects installed.
2022-06-07 13:37:33,519 INFO    MainThread:161716 [wandb_init.py:init():685] run started, returning control to user process
2022-06-07 13:37:33,519 INFO    MainThread:161716 [wandb_run.py:_config_callback():1129] config_cb None None {'batch_size': 64, 'experiment_name': 'channel-wise diversity', 'evo_gens': 50, 'evo_pop': 20, 'evo_dataset_for_novelty': 'cifar10', 'evo_num_runs': 5, 'evo_tourney_size': 4, 'evo_num_winners': 2, 'evo_num_children': 20, 'diversity_type': 'absolute', 'experiment_type': 'evolution'}
