2022-06-01 12:00:15,293 INFO    BackendThr:57712 [internal.py:wandb_internal():92] W&B internal server running at pid: 57712, started at: 2022-06-01 12:00:15.292551
2022-06-01 12:00:15,293 INFO    MainThread:57712 [wandb_init.py:init():534] backend started and connected
2022-06-01 12:00:15,293 DEBUG   MainThread:57712 [config_util.py:dict_from_config_file():102] no default config file found in config-defaults.yaml
2022-06-01 12:00:15,294 INFO    MainThread:57712 [wandb_init.py:init():598] updated telemetry
2022-06-01 12:00:15,296 INFO    WriterThread:57712 [datastore.py:open_for_write():77] open: C:\Users\Jordan\Learning\UVM\Research Projects\Novel-Feature-Detector\wandb\offline-run-20220601_120015-o94o2ach\run-o94o2ach.wandb
2022-06-01 12:00:15,334 INFO    MainThread:57712 [wandb_init.py:init():660] starting run threads in backend
2022-06-01 12:00:15,338 DEBUG   HandlerThread:57712 [handler.py:handle_request():141] handle_request: run_start
2022-06-01 12:00:15,361 DEBUG   HandlerThread:57712 [meta.py:__init__():37] meta init
2022-06-01 12:00:15,361 DEBUG   HandlerThread:57712 [meta.py:__init__():51] meta init done
2022-06-01 12:00:15,361 DEBUG   HandlerThread:57712 [meta.py:probe():211] probe
2022-06-01 12:00:15,370 DEBUG   HandlerThread:57712 [meta.py:_setup_git():201] setup git
2022-06-01 12:00:15,440 DEBUG   HandlerThread:57712 [meta.py:_setup_git():208] setup git done
2022-06-01 12:00:15,441 DEBUG   HandlerThread:57712 [meta.py:_save_pip():55] save pip
2022-06-01 12:00:15,441 DEBUG   HandlerThread:57712 [meta.py:_save_pip():69] save pip done
2022-06-01 12:00:15,441 DEBUG   HandlerThread:57712 [meta.py:_save_conda():76] save conda
2022-06-01 12:00:15,444 ERROR   HandlerThread:57712 [meta.py:_save_conda():85] Error saving conda packages
Traceback (most recent call last):
  File "C:\Users\Jordan\anaconda3\envs\EC2\lib\site-packages\wandb\sdk\internal\meta.py", line 81, in _save_conda
    subprocess.call(
  File "C:\Users\Jordan\anaconda3\envs\EC2\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Jordan\anaconda3\envs\EC2\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Jordan\anaconda3\envs\EC2\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
2022-06-01 12:00:15,446 DEBUG   HandlerThread:57712 [meta.py:_save_conda():86] save conda done
2022-06-01 12:00:15,446 DEBUG   HandlerThread:57712 [meta.py:probe():249] probe done
2022-06-01 12:00:15,452 INFO    MainThread:57712 [wandb_run.py:_console_start():1896] atexit reg
2022-06-01 12:00:15,452 INFO    MainThread:57712 [wandb_run.py:_redirect():1769] redirect: SettingsConsole.WRAP
2022-06-01 12:00:15,453 INFO    MainThread:57712 [wandb_run.py:_redirect():1806] Wrapping output streams.
2022-06-01 12:00:15,453 INFO    MainThread:57712 [wandb_run.py:_redirect():1830] Redirects installed.
2022-06-01 12:00:15,453 INFO    MainThread:57712 [wandb_init.py:init():685] run started, returning control to user process
2022-06-01 12:00:15,454 INFO    MainThread:57712 [wandb_run.py:_config_callback():1129] config_cb None None {'batch_size': 64, 'experiment_name': 'test relative diversity', 'evo_gens': 5, 'evo_pop': 10, 'evo_dataset_for_novelty': 'cifar10', 'evo_num_runs': 1, 'evo_tourney_size': 4, 'evo_num_winners': 2, 'evo_num_children': 10, 'diversity_type': 'relative', 'experiment_type': 'evolution'}
