Traceback (most recent call last):
  File "C:\Users\Jordan\Learning\UVM\Research\novel-feature-detector\train_and_eval.py", line 104, in <module>
    run()
  File "C:\Users\Jordan\Learning\UVM\Research\novel-feature-detector\train_and_eval.py", line 62, in run
    data_module = helper.get_data_module(args.dataset, args.batch_size)
  File "C:\Users\Jordan\Learning\UVM\Research\novel-feature-detector\helper_hpc.py", line 56, in get_data_module
    data_module = CIFAR100DataModule(batch_size=batch_size)
TypeError: CIFAR100DataModule.__init__() got an unexpected keyword argument 'batch_size'